name: RCV Academy Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # 1. Download App Code into 'test-app' folder
      - name: Checkout Demo eCommerce test application code
        uses: actions/checkout@v4
        with:
          repository: rcvacademy/rcv-academy-automation-practice-app
          path: test-app

      # 2. Download Test Automation Code into 'automation' folder
      - name: Checkout test automation code
        uses: actions/checkout@v4
        with:
          path: automation

      # 3. Install and Start the test App (Background)
      - name: Install and start test application
        working-directory: test-app
        run: |
          npm install
          npm start &
          # This ensures the app is actually up before moving to tests
          npx wait-on http://localhost:3000 

      # 4. Install Automation Dependencies
      - name: Install automation dependencies
        working-directory: automation
        run: npm ci

      # 5. Install Playwright Browsers
      - name: Install Playwright Browsers
        working-directory: automation
        run: npx playwright install --with-deps

      # 6. Run Playwright tests
      - name: Run Playwright tests
        working-directory: automation
        run: npm run test:qa

      # 7. Upload Report
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: automation/playwright-report/
          retention-days: 30
